remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Brandon Julian
logo: "/images/headshot.jpg?raw=true"
description: Personal website for projects, blog, and information.
