theme: jekyll-theme-minimal
title: Brandon Julian
logo: "https://github.com/bdjulian/bdjulian.github.io/blob/main/images/headshot.jpg?raw=true"
description: A website to contain my information and projects
